# Generated by Django 5.0.7 on 2024-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='moods',
            field=models.ManyToManyField(to='mood.mood'),
        ),
    ]
