# Generated by Django 5.0.7 on 2024-07-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_moods'),
        ('genre', '0003_alter_genre_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='genre.genre'),
            preserve_default=False,
        ),
    ]
