# Generated by Django 5.0.7 on 2024-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_moods'),
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='moods',
            field=models.ManyToManyField(blank=True, null=True, to='mood.mood'),
        ),
    ]
