# Generated by Django 5.0.7 on 2024-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to='artist/images')),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
