# Generated by Django 5.0.7 on 2024-07-22 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
        ('genre', '0001_initial'),
        ('mood', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='track/images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='track/files')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='album.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artist.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='genre.genre')),
                ('moods', models.ManyToManyField(blank=True, related_name='tracks', to='mood.mood')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='playlist.playlist')),
            ],
        ),
    ]
