# Generated by Django 5.0.7 on 2024-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(default=None, upload_to='track/files'),
            preserve_default=False,
        ),
    ]
