# Generated by Django 5.0.7 on 2024-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
