# Generated by Django 5.0.7 on 2024-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_name_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
